vars:
  stage: lab
  environment: lab 

import:
  - catalog/global

components:
  terraform:
    vpc:
      metadata: 
        componet: "vpc"        
      vars:
        create_database_subnet_group: true
        create_database_subnet_route_table: true
        enable_nat_gateway: true
        single_nat_gateway: true
        one_nat_gateway_per_az: false
    
        owners: aws
        name: vpc-lab-terraform
      
        cidr: 10.0.0.0/16 
        azs:
          - us-east-1c
          - us-east-1d
        public_subnets:
          - 10.0.1.0/24
          - 10.0.3.0/24
        private_subnets:
          - 10.0.2.0/24
          - 10.0.4.0/24
        database_subnets:
          - 10.0.151.0/24
          - 10.0.152.0/24
    ssm:
      settings:
        depends_on:
          1:
            component: "vpc"          
      metadata: 
         componet: "ssm"
      vars:
        s3_bucket: ssm
        vpc_id: '{{ (atmos.Component "vpc" .stack).outputs.vpc_id }}' 
        cidr: '{{ (atmos.Component "vpc" .stack).outputs.vpc_cidr_block }}'
        ssm_role: ssm

    test:
       metadata:
          componet: "test"
       vars:
        vpc_id: '{{ (atmos.Component "vpc" .stack).outputs.vpc_id }}' 
        private_subnets: '{{ toRawJson ((atmos.Component "vpc" .stack).outputs.private_subnets) }}'
    codebuild:
      metadata:
          componet: "codebuild"
      vars:
        secret_token_arn : "arn:aws:secretsmanager:us-east-1:106613608949:secret:GITHUB-TOKEN-BzZcBD"     
    ec2:
      settings:
        depends_on:
          1:
            component: "vpc" 
          2:
            component: "ssm" 
      metadata:
          componet: "ec2"
      vars:
        ami: "ami-04a81a99f5ec58529"
        private_subnets: '{{ toRawJson ((atmos.Component "vpc" .stack).outputs.private_subnets) }}'
        cidr: '{{ (atmos.Component "vpc" .stack).outputs.vpc_cidr_block }}'
        vpc_id: '{{ (atmos.Component "vpc" .stack).outputs.vpc_id }}'
        key_name: "Key1"
        ssm_role_name: '{{ (atmos.Component "ssm" .stack).outputs.ssm_role_name }}'       
    oidc:
       metadata:
          componet: "oidc"
       vars:
         repos:  ["Mudpuppy12/*"]